# Generated by Django 3.1.3 on 2021-11-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
