# Generated by Django 3.1.3 on 2021-12-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
