# Generated by Django 3.2.8 on 2022-01-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20220108_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
