# Generated by Django 3.2.8 on 2022-01-11 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_alter_newpost_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likepost',
            field=models.ManyToManyField(default=False, related_name='likepost', to=settings.AUTH_USER_MODEL),
        ),
    ]
